apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: memory-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: demo.memory.rules
      rules:
        - alert: HighNodeMemory
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 20
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage on {{ $labels.instance }}"
            description: "Node memory usage > 20% for 2 minutes."
